package org.alfime.apoyo.exceptions;

public class UsuarioNotFoundException extends Throwable {
    public UsuarioNotFoundException(String message) {
        super(message);
    }
}
